language: generic
dist: xenial
sudo: false
env:
  - [ "PREFIX=/usr/lib/llvm-4.0/lib/cmake", "BIN=/usr/lib/llvm-4.0/bin" ]
addons:
  apt:
    sources: [ "ubuntu-toolchain-r-test", "llvm-toolchain-trusty-4.0" ]
    packages: [ "libboost-all-dev", "tcl-dev", "tk-dev", "emacs", "clang-4.0", "libclang-4.0-dev", "llvm-4.0-dev", "clang-format-4.0", "clang-tidy-4.0" ]

before_script:
  # Fix clang cmake dirs
  - sudo -E ln -sn /usr/share/llvm-4.0/cmake /usr/lib/llvm-4.0/lib/cmake/clang
  - sudo -E ln -sn /usr/share/llvm-4.0/cmake /usr/lib/llvm-4.0/lib/cmake/clang-4.0
  - sudo -E ln -s  /usr/bin/*                /usr/lib/llvm-4.0/bin || true
jobs:
  include:
    - stage: compiling and checking sources
      script:
        - mkdir -p ../cache/vm ../cache/boostenv
        - mv vm/boostenv/main/cached ../cache/boostenv
        - mv vm/vm/main/cached ../cache/vm
        - export SOURCES=$(pwd) && mkdir ../build && cd ../build
        - cmake -DCMAKE_BUILD_TYPE=Release -DMOZART_BOOST_USE_STATIC_LIBS=False -DCMAKE_PROGRAM_PATH=$BIN -DCMAKE_PREFIX_PATH=$PREFIX -DMOZART_CACHED_BUILD=OFF $SOURCES
        - make -B gensources genboostsources VERBOSE=1
        - cd ..
        - diff -q -r cache/boostenv/cached build/vm/boostenv/main/generated
        - diff -Npur cache/boostenv/cached build/vm/boostenv/main/generated
        - diff -q -r cache/vm/cached build/vm/vm/main/generated
        - diff -Npur cache/vm/cached build/vm/vm/main/generated

    - stage: compiling with pre-generated sources
      script:
        - export SOURCES=$(pwd) && mkdir ../build && cd ../build
        - cmake -DCMAKE_BUILD_TYPE=Release -DMOZART_BOOST_USE_STATIC_LIBS=False -DCMAKE_PROGRAM_PATH=$BIN -DCMAKE_PREFIX_PATH=$PREFIX $SOURCES
        - make dist VERBOSE=1
        - make VERBOSE=1
        - make check

    - sudo: true
      env:
        matrix:
          - BUILD_FLAVOR=fedora
          - BUILD_FLAVOR=ubuntu
      before_script: ""
      addons:
      script: bash ci/$BUILD_FLAVOR.sh

